// <auto-generated />
using System;
using BookService.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookService.Repository.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250212213447_Trades")]
    partial class Trades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MB")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookAuthorsJoinTable", b =>
                {
                    b.Property<int>("AuthorBooksId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.HasKey("AuthorBooksId", "AuthorsId");

                    b.HasIndex("AuthorsId");

                    b.ToTable("BookAuthorsJoinTable", "MB");
                });

            modelBuilder.Entity("BookService.Domain.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Author", "MB");
                });

            modelBuilder.Entity("BookService.Domain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Book", "MB");
                });

            modelBuilder.Entity("BookService.Domain.Models.BookExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InitiatorBookItemId")
                        .HasColumnType("int");

                    b.Property<int>("InitiatorUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverBookItemId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BookExchange", "MB");
                });

            modelBuilder.Entity("BookService.Domain.Models.BookPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Lat")
                        .HasColumnType("int");

                    b.Property<int>("Long")
                        .HasColumnType("int");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BookPoint", "MB");
                });

            modelBuilder.Entity("BookService.Domain.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ImageType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserBookItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Image", "MB");
                });

            modelBuilder.Entity("BookService.Domain.Models.UserBookItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookPointId")
                        .HasColumnType("int");

                    b.Property<int>("BookReferenceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemImageId")
                        .HasColumnType("int");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookPointId");

                    b.HasIndex("BookReferenceId");

                    b.HasIndex("ItemImageId")
                        .IsUnique()
                        .HasFilter("[ItemImageId] IS NOT NULL");

                    b.ToTable("UserBookItem", "MB");
                });

            modelBuilder.Entity("BookService.Domain.Models.UserLikesBooks", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserBookItemId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "UserBookItemId");

                    b.HasIndex("UserBookItemId");

                    b.ToTable("UserLikesBooks", "MB");
                });

            modelBuilder.Entity("BookAuthorsJoinTable", b =>
                {
                    b.HasOne("BookService.Domain.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("AuthorBooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookService.Domain.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookService.Domain.Models.UserBookItem", b =>
                {
                    b.HasOne("BookService.Domain.Models.BookPoint", "BookPoint")
                        .WithMany()
                        .HasForeignKey("BookPointId");

                    b.HasOne("BookService.Domain.Models.Book", "BookReference")
                        .WithMany("BookItems")
                        .HasForeignKey("BookReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookService.Domain.Models.Image", "ItemImage")
                        .WithOne("UserBookItem")
                        .HasForeignKey("BookService.Domain.Models.UserBookItem", "ItemImageId");

                    b.Navigation("BookPoint");

                    b.Navigation("BookReference");

                    b.Navigation("ItemImage");
                });

            modelBuilder.Entity("BookService.Domain.Models.UserLikesBooks", b =>
                {
                    b.HasOne("BookService.Domain.Models.UserBookItem", "userBookItem")
                        .WithMany("UserLikes")
                        .HasForeignKey("UserBookItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userBookItem");
                });

            modelBuilder.Entity("BookService.Domain.Models.Book", b =>
                {
                    b.Navigation("BookItems");
                });

            modelBuilder.Entity("BookService.Domain.Models.Image", b =>
                {
                    b.Navigation("UserBookItem");
                });

            modelBuilder.Entity("BookService.Domain.Models.UserBookItem", b =>
                {
                    b.Navigation("UserLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
